version: '3'
services:
  web:
    build: ./nginx
    ports:
      - '8080:80'
    links:
      - php-fpm
    volumes:
      - ./data/public:/var/www/html/public
    depends_on:
      - php-fpm
  php-fpm:
    volumes:
      - ./data:/var/www/html
    build: ./php-fpm
    links:
      - db
    depends_on:
      - db
  db:
    build: ./mysql
    container_name: mysql_host_image
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --default-authentication-plugin=mysql_native_password
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_USER: user
      MYSQL_PASSWORD: userpass
      MYSQL_DATABASE: sample
      TZ: 'Asia/Tokyo'
